trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install dotnet-ef --global'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'ef'
    arguments: 'migrations script -o migration.sql --idempotent'
    workingDirectory: '$(System.DefaultWorkingDirectory)/ArenaBrawl'

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Visual Studio Professional with MSDN(48921dc3-b5bc-4bdd-8a68-f09da744c789)'
    AuthenticationType: 'connectionString'
    ConnectionString: '$(dbconnectionstring)'
    deployType: 'SqlTask'
    SqlFile: '$(System.DefaultWorkingDirectory)/ArenaBrawl/migration.sql'
    IpDetectionMethod: 'AutoDetect' 

- task: AzureAppServiceSettings@1
  inputs:
    azureSubscription: 'Visual Studio Professional with MSDN(48921dc3-b5bc-4bdd-8a68-f09da744c789)'
    appName: 'arenabrawl'
    resourceGroupName: 'ArenaBrawl'
    appSettings: |
      [
        {
          "name": "Payments:ApiKey",
          "value": "$(stripePaymentApiSecret)",
          "slotSetting": true
        },
        {
          "name": "Payments:SuccessUrl",
          "value": "https://arenabrawl.net/thanks?session_id={CHECKOUT_SESSION_ID}",
          "slotSetting": true
        },
        {
          "name": "Payments:CancelUrl",
          "value": "https://arenabrawl.net/",
          "slotSetting": true
        },
        {
          "name": "Payments:PublicKey",
          "value": "pk_live_p1blPTmJBikvkfqlcWjsURbP00SY4ItjgB",
          "slotSetting": true
        }
      ]

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Professional with MSDN(48921dc3-b5bc-4bdd-8a68-f09da744c789)'
    appType: 'webApp'
    WebAppName: 'arenabrawl'
    packageForLinux: '**/*.zip'